-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, REST_INFO.FAVORITES
FROM 
(
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) TEMP
LEFT JOIN REST_INFO 
ON REST_INFO.FOOD_TYPE = TEMP.FOOD_TYPE 
AND REST_INFO.FAVORITES = TEMP.FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC;