-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 0 as hour
    UNION ALL
    SELECT HOUR + 1 FROM time WHERE HOUR < 23
)
SELECT TIME.HOUR, IFNULL(COUNT, 0) COUNT
FROM TIME
LEFT JOIN (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) TEMP
ON TEMP.HOUR = TIME.HOUR;