-- 코드를 입력하세요
SELECT temp.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM 
(
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) temp
JOIN FOOD_PRODUCT 
ON FOOD_PRODUCT.CATEGORY = temp.CATEGORY 
AND FOOD_PRODUCT.PRICE = temp.MAX_PRICE
ORDER BY MAX_PRICE DESC;