-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW
JOIN MEMBER_PROFILE
ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE REST_REVIEW.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM (
        SELECT MEMBER_ID, COUNT(*) COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT DESC
        LIMIT 1
    ) TEMP
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;