-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES 
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%y-%m') = '22-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;