-- 코드를 입력하세요
SELECT FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) TOTAL_SALES
FROM FOOD_ORDER
JOIN FOOD_PRODUCT
ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY FOOD_ORDER.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_ORDER.PRODUCT_ID;