-- 코드를 입력하세요
SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR ON RR.REST_ID = RI.REST_ID	 
WHERE ADDRESS LIKE "서울%"
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;